name: Check
on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Types
        run: npm run type
      - name: Test
        run: npm run test